backend:
  name: github
  repo: manspeterson/albin-site # Path to your Github repository
  branch: master # Branch to update
  site_domain: albinsjodin.netlify.com # Your Netlify site address if different from host

media_folder : "img"

collections:
  - name: "portfolio" # Used in routes, e.g. /admin/collections/blog
    label: "Portfolio" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Category", name: "categories", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Featured Image", name: "image-url", widget: "image"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Video", name: "video", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Datum (sortering)", name: "date", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - name: "about" # Used in routes, e.g. /admin/collections/blog
        label: "About" # Used in the UI
        file: "about.md" # The path to the folder where the documents are stored
        fields: # The fields for each document, usually in front matter
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "hidden"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Clients", name: "clients", widget: "list"}
          - {label: "Body", name: "body", widget: "markdown"}
